version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  flask_app:
    build: .
    container_name: flask_auth
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - JWT_SECRET_KEY=your_jwt_secret
